### ISSUE TITLE
This only update string?

### ISSUE THREAD

**Issue by huy-lv** [localizely/flutter-ota-sample-app#1]
As the demo video in README, this library only update string in app, isn't it? Can it update logic code?

**Comment by lzoran** [comment]
Hi @huy-lv,

Yes, you are right.
With Localizely SDK you can instantly update translations for your Flutter applications over the air. There is no need to release a new version to the App Store or Google Play.
The most common use cases are correcting typos, optimizing texts, or updating translations on the fly.

**Comment by huy-lv** [comment]
Actually this can be achieve by Firebase Remote config

**Comment by aleksakrstic** [comment]
Hi @huy-lv 
While you might find some way to use Remote Config for apps with just one end-user language, it is not intended for translations management and you will have problems for multi-lingual apps.
However, if something like that fits your use-case, go ahead.
