### ISSUE TITLE
Over the air offline

### ISSUE THREAD

**Issue by maradic** [localizely/flutter-ota-sample-app#2]
I follow all steps for setting your plugin. 
I noticed over the air feature not working when you are offline. 
Steps:
Push new update in console. 
Open app when have data, works all good.
Open app again in offline i don't have translations from previous step. 

Can you help me to make cache work in offline mode.

**Comment by aleksakrstic** [comment]
Hi @maradic 
Offline mode (caching) is already planned to be supported out of the box by SDK, in one of the upcoming releases.
No exact date yet, but probably around January-February 2021.

**Comment by maradic** [comment]
Is it implemented?

**Comment by goranluledzija** [comment]
Yes, with version `1.3.0` https://pub.dev/packages/localizely_sdk/changelog
