### ISSUE TITLE
Getting a crash when integrated with Google ML vision lib in Android

### ISSUE THREAD

**Issue by sidfluidra** [localizely/flutter-ota-sample-app#3]
I have integrated OCR scanner using  ML vision library google_ml_vision: ^0.0.7. What I have found is that if I used the localizely in my pubspec.yaml file the OCR won't work and the application gets crashed.

E/AndroidRuntime(13622): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/mlkit/vision/common/internal/Detector;
E/AndroidRuntime(13622): 	at com.brianmtully.flutter.plugins.googlemlvision.MlVisionHandler.handleDetection(GoogleMlVisionHandler.java:74)
E/AndroidRuntime(13622): 	at com.brianmtully.flutter.plugins.googlemlvision.MlVisionHandler.onMethodCall(GoogleMlVisionHandler.java:37)
E/AndroidRuntime(13622): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime(13622): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(13622): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(13622): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/AndroidRuntime(13622): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(13622): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(13622): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(13622): 	at android.app.ActivityThread.main(ActivityThread.java:8057)
E/AndroidRuntime(13622): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13622): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
E/AndroidRuntime(13622): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
E/AndroidRuntime(13622): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.mlkit.vision.common.internal.Detector" on path: DexPathList[[zip file "/data/app/~~HP81Vk22Kn1e8Vs4_kyvqw==/com.zodiac.fluidrapro-x3KleMT3cyux_kMnXVYHXg==/base.apk"],

**Comment by lzoran** [comment]
Hi @sidfluidra,

I've tried to reproduce this issue (add the `google_ml_vision: ^0.0.7` as a dependency), but it seems that everything works fine. 😕 

Could you share with us more details on how to reproduce this issue (flutter version, `localizely_sdk` version, `flutter_intl` config, `compileSdkVersion` and `minSdkVersion` configs from `android/app/build.gradle`,  reproduction steps with this sample app)?

Also, in case you are using the latest version of the `localizely_sdk`, could you check if downgrading it to `2.3.0` helps? The latest version of the `localizely_sdk` depends on the `mobile_scanner`, and maybe there is some disagreement between the `mobile_scanner` and `google_ml_vision` packages.

**Comment by sidfluidra** [comment]
Hi,

I had downgraded the version to 2.3.0 and it worked for me. Thanks for
helping me out .

**Comment by sidfluidra** [comment]
Hi ,

Adding the dependency did work for you, but when you try to read the text
using OCR than it ultimately crashes the application.

**Comment by lzoran** [comment]
This should be fixed with `localizely_sdk 2.5.0`.
Closing this issue as resolved.
In case you notice any irregularities, please open it again.
