### ISSUE TITLE
How to setting OTA with In-Context Editing features together?

### ISSUE THREAD

**Issue by ska2519** [localizely/flutter-ota-sample-app#4]
I want to use the **FLUTTER OVER-THE-AIR UPDATES** function with the **Flutter In-Context Editing** function in
`localizely_sdk: ^2.4.0` version.

I've tried setting it up in several ways.

Exception has occurred.
`SdkException (SdkException: Metadata configuration has not been set. Please ensure 'ota_enabled' is set to 'true' within 'flutter_intl/localizely' section of the 'pubspec.yaml' file, and that 'updateTranslations' method is called after localization delegates initialization .)`

occurs.

I wonder in what order and in what command to create files.

I would appreciate it if you could make a sample using the two functions together 🙏

**Comment by lzoran** [comment]
Hi @ska2519,

The attached message says that you are missing metadata configuration. To solve that, you need to set `ota_enabled` to `true` in the `pubspec.yaml` file.

```
flutter_intl:
  enabled: true
  localizely:
    ota_enabled: true
```

*Note: Flutter Over-the-Air depends on the generated code from the Flutter Intl plugin*

Perhaps it would be easiest to explain how to do it by extending the [flutter-ota-sample-app](https://github.com/localizely/flutter-ota-sample-app) with Flutter In-Context Editing feature. To achieve that, you need to do the following:

- Update `localizely_sdk` to `^2.4.0` in the `pubspec.yaml` file & run `flutter pub get`
- Update `Localizely.init` method with real **SDK token** and **Distribution ID** values from Localizely in the `main.dart` file
- Replace `runApp(const MyApp());` with `runApp(const LocalizelyInContextEditing(enabled: true, child: MyApp()));` in the `main.dart` file
- Update android `minSdkVersion` to `21` (replace `minSdkVersion flutter.minSdkVersion` with `minSdkVersion 21`) in the `android/app/build.gradle` file

Useful links:
- [Flutter Over-the-Air docs](https://localizely.com/flutter-over-the-air/)
- [Flutter Over-the-Air sample app](https://github.com/localizely/flutter-ota-sample-app)
- [Flutter In-Context Editing docs](https://localizely.com/flutter-in-context-editing/?tab=using-flutter-intl)
- [Flutter In-Context Editing sample app](https://github.com/localizely/flutter-in-context-editing-example/tree/flutter-intl-example) (the `flutter-intl-example` branch is for the Flutter Intl plugin)
- [Flutter localization with Flutter Intl plugin](https://localizely.com/blog/flutter-localization-step-by-step/?tab=automated-using-flutter-intl)

Hope it helped!

**Comment by ska2519** [comment]
> Hi @ska2519,
> 
> The attached message says that you are missing metadata configuration. To solve that, you need to set `ota_enabled` to `true` in the `pubspec.yaml` file.
> 
> ```
> flutter_intl:
>   enabled: true
>   localizely:
>     ota_enabled: true
> ```
> 
> _Note: Flutter Over-the-Air depends on the generated code from the Flutter Intl plugin_
> 
> Perhaps it would be easiest to explain how to do it by extending the [flutter-ota-sample-app](https://github.com/localizely/flutter-ota-sample-app) with Flutter In-Context Editing feature. To achieve that, you need to do the following:
> 
> * Update `localizely_sdk` to `^2.4.0` in the `pubspec.yaml` file & run `flutter pub get`
> * Update `Localizely.init` method with real **SDK token** and **Distribution ID** values from Localizely in the `main.dart` file
> * Replace `runApp(const MyApp());` with `runApp(const LocalizelyInContextEditing(enabled: true, child: MyApp()));` in the `main.dart` file
> * Update android `minSdkVersion` to `21` (replace `minSdkVersion flutter.minSdkVersion` with `minSdkVersion 21`) in the `android/app/build.gradle` file
> 
> Useful links:
> 
> * [Flutter Over-the-Air docs](https://localizely.com/flutter-over-the-air/)
> * [Flutter Over-the-Air sample app](https://github.com/localizely/flutter-ota-sample-app)
> * [Flutter In-Context Editing docs](https://localizely.com/flutter-in-context-editing/?tab=using-flutter-intl)
> * [Flutter In-Context Editing sample app](https://github.com/localizely/flutter-in-context-editing-example/tree/flutter-intl-example) (the `flutter-intl-example` branch is for the Flutter Intl plugin)
> * [Flutter localization with Flutter Intl plugin](https://localizely.com/blog/flutter-localization-step-by-step/?tab=automated-using-flutter-intl)
> 
> Hope it helped!

how to set in `localizationsDelegates` ?
`AppLocalizations.localizationsDelegates` is make below Exception
```
Exception has occurred.
SdkException (SdkException: Metadata configuration has not been set. Please ensure 'ota_enabled' is set to 'true' within 'flutter_intl/localizely' section of the 'pubspec.yaml' file, and that 'updateTranslations' method is called after localization delegates initialization .)
```


### **additional information**

I add customLocalizelyLocalizationsDelegates for use OTA with In-Context Editing features together.
can i use like this?


```dart
  final customLocalizelyLocalizationsDelegates =
        AppLocalizations.localizationsDelegates.toList();
    customLocalizelyLocalizationsDelegates.insert(
        customLocalizelyLocalizationsDelegates.length, S.delegate);

    return MaterialApp(
      localizationsDelegates: customLocalizelyLocalizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
    )
```

**Comment by lzoran** [comment]
The Flutter Over-the-Air feature works only with the code generated with the Flutter Intl plugin. The Flutter In-Context Editing feature works with the code generated with the [Flutter Intl plugin](https://github.com/localizely/flutter-in-context-editing-example/tree/flutter-intl-example) and with the [gen_l10n tool](https://github.com/localizely/flutter-in-context-editing-example). To use both features, you will need to use code generated with the Flutter Intl plugin.

There are plans to extend the Flutter Over-the-Air feature to work with the code generated with the gen_l10n tool, but I don't know exactly when that will be available.

**Comment by ska2519** [comment]
Thanks for your kindness reply 👍 
I tried few days for use both features..
I understand can not use both features together.
I will setup OTA feature in my App.

hope to use both features together soon :)
Looks like 2 packages in now.
I like you guys service :)
